-- SPDX-License-Identifier: Apache-2.0
-- Licensed to the Ed-Fi Alliance under one or more agreements.
-- The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
-- See the LICENSE and NOTICES files in the project root for more information.

BEGIN;

    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Active Shooter', 'Active Shooter', 'Active Shooter', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Avalanche', 'Avalanche', 'Avalanche', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Cyberattack', 'Cyberattack', 'Cyberattack', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Earthquake', 'Earthquake', 'Earthquake', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Extreme Heat', 'Extreme Heat', 'Extreme Heat', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Financial Emergency', 'Financial Emergency', 'Financial Emergency', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Flood', 'Flood', 'Flood', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Hurricane', 'Hurricane', 'Hurricane', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Landslide', 'Landslide', 'Landslide', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Novel Pandemic', 'Novel Pandemic', 'Novel Pandemic', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Nuclear Explosion', 'Nuclear Explosion', 'Nuclear Explosion', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Other', 'Other', 'Other', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Power Outage', 'Power Outage', 'Power Outage', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Thunderstorm, Lightning, or Hail', 'Thunderstorm, Lightning, or Hail', 'Thunderstorm, Lightning, or Hail', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Tornado', 'Tornado', 'Tornado', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Tsunami', 'Tsunami', 'Tsunami', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Volcano', 'Volcano', 'Volcano', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Wildfires', 'Wildfires', 'Wildfires', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/CrisisTypeDescriptor', 'Winter Storm', 'Winter Storm', 'Winter Storm', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/DisplacedStudentStatusDescriptor', 'Displaced', 'Displaced', 'Displaced', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/DisplacedStudentStatusDescriptor', 'Not Displaced', 'Not Displaced', 'Not Displaced', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/DisplacedStudentStatusDescriptor', 'Pending Displacement', 'Pending Displacement', 'Pending Displacement', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/DisplacedStudentStatusDescriptor', 'Unknown', 'Unknown', 'Unknown', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', '1vCOV', 'COVID-19', 'COVID-19', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'DEN4CYD', 'Dengue', 'Dengue', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'DTaP', 'Diphtheria, tetanus and acellular pertussis', 'Diphtheria, tetanus and acellular pertussis', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'HepA', 'Hepatitis A', 'Hepatitis A', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'HepB', 'Hepatitis B', 'Hepatitis B', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'Hib', 'Haemophilus influenzae type b', 'Haemophilus influenzae type b', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'HPV', 'Human papillomavirus', 'Human papillomavirus', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'IIV4', 'Influenza', 'Influenza', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'IPV', 'Inactivated poliovirus', 'Inactivated poliovirus', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'LAIV4', 'Influenza', 'Influenza', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'MenACWY', 'Meningococcal serogroup A,C,W,Y', 'Meningococcal serogroup A,C,W,Y', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'MenB', 'Meningococcal serogroup B', 'Meningococcal serogroup B', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'MMR', 'Measles, mumps, rubella', 'Measles, mumps, rubella', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'Mpox', 'Mpox', 'Mpox', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'PCV', 'Pneumococcal conjugate', 'Pneumococcal conjugate', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'RSV', 'Respiratory syncytial virus', 'Respiratory syncytial virus', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'RV', 'Rotavirus', 'Rotavirus', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/ImmunizationTypeDescriptor', 'VAR', 'Varicella (chickenpox)', 'Varicella (chickenpox)', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/NonMedicalImmunizationExemptionDescriptor', 'Other', 'Other', 'Other', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/NonMedicalImmunizationExemptionDescriptor', 'Philosophical', 'Philosophical belief', 'Philosophical belief', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/NonMedicalImmunizationExemptionDescriptor', 'Religious', 'Religious belief', 'Religious belief', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - CTE', 'Eligible because of CTE participation', 'Student is eligible for transportation at public expense because of their participation in a CTE program.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Desegregation', 'Eligible because of desegregation', 'Student is eligible for transportation at public expense because of a locally initiated or court mandated program for achieving racial or cultural integration or for ending previous segregation.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Disability', 'Eligible because of disability', 'Student is eligible for transportation at public expense because of the their disability and IEP.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Distance', 'Eligible because of distance', 'Student is eligible for transportation at public expense because of the distance between school and transportation address.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Health Impaired', 'Eigible because of health impairement', 'Student is eligible for transportation at public expense because of the health impairement that doesn''t make the student eligible for IEP', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Homelessness', 'Eligible because of homeless status', 'Student is eligible for transportation at public expense because of being homeless as defined by the McKinney-Vento Act.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Other', 'Eligible for other reason', 'Student is eligible for transportation at public expense because of the other reasons not listed.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Shelter Care', 'Eligible from shelter care facility', 'Student is eligible for transportation at public expense because of their short or long term stay at a shelter care that is not covered by the McKinney-Vento Act.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Special Instruction', 'Eligible because of special instruction', 'Student is eligible for transportation at public expense because of the special instruction not due to a disability.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Eligible - Unsafe Walk', 'Eligible because of hazardous conditions', 'Student is eligible for transportation at public expense because of the hazardous conditions that makes the walk between the school and the transportation address unsafe for the student.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor', 'Not Eligible', 'Not Eligible', 'Student is not eligeble for transporation at public expense.', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationTypeDescriptor', 'General Public Transportation', 'General Public Transportation', 'General Public Transportation', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationTypeDescriptor', 'Responsible for own transportation', 'Responsible for own transportation', 'Responsible for own transportation', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationTypeDescriptor', 'School Bus', 'School Bus', 'School Bus', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationTypeDescriptor', 'School Van or SUV', 'School Van or SUV', 'School Van or SUV', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TransportationTypeDescriptor', 'Special Needs Bus', 'Special Needs Bus', 'Special Needs Bus', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDayofWeekDescriptor', 'Friday', 'Friday', 'Friday', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDayofWeekDescriptor', 'Monday', 'Monday', 'Monday', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDayofWeekDescriptor', 'Saturday', 'Saturday', 'Saturday', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDayofWeekDescriptor', 'Sunday', 'Sunday', 'Sunday', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDayofWeekDescriptor', 'Thursday', 'Thursday', 'Thursday', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDayofWeekDescriptor', 'Tuesday', 'Tuesday', 'Tuesday', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDayofWeekDescriptor', 'Wednesday', 'Wednesday', 'Wednesday', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDirectionDescriptor', 'From School', 'From School', 'From School', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDirectionDescriptor', 'To and From School', 'To and From School', 'To and From School', now()::timestamp, now()::timestamp, gen_random_uuid());
    INSERT INTO edfi.descriptor ("namespace",codevalue,shortdescription,description,createdate,lastmodifieddate,"id") VALUES ('uri://ed-fi.org/TravelDirectionDescriptor', 'To School', 'To School', 'To School', now()::timestamp, now()::timestamp, gen_random_uuid());

    INSERT INTO edfi.crisistypedescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/CrisisTypeDescriptor';
    INSERT INTO edfi.displacedstudentstatusdescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/DisplacedStudentStatusDescriptor';
    INSERT INTO edfi.immunizationtypedescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/ImmunizationTypeDescriptor';
    INSERT INTO edfi.nonmedicalimmunizationexemptiondescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/NonMedicalImmunizationExemptionDescriptor';
    INSERT INTO edfi.transportationpublicexpenseeligibilitytypedescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/TransportationPublicExpenseEligibilityTypeDescriptor';
    INSERT INTO edfi.transportationtypedescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/TransportationTypeDescriptor';
    INSERT INTO edfi.traveldayofweekdescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/TravelDayofWeekDescriptor';
    INSERT INTO edfi.traveldirectiondescriptor SELECT descriptorid FROM edfi.descriptor WHERE "namespace" = 'uri://ed-fi.org/TravelDirectionDescriptor';

END;
